"""baseline

Revision ID: 0001_baseline
Revises: 
Create Date: 2026-06-25 12:28:29.647910
"""
from alembic import op
import sqlalchemy as sa


revision = '0001_baseline'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('label_kind', sa.String(length=40), nullable=False),
    sa.Column('owner', sa.String(length=120), nullable=False),
    sa.Column('lot_method', sa.String(length=10), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('hourly_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hour_start', sa.DateTime(), nullable=False),
    sa.Column('price_usd', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hour_start')
    )
    op.create_table('llm_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('api_key', sa.String(length=255), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('node_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('electrum_host', sa.String(length=255), nullable=False),
    sa.Column('electrum_port', sa.Integer(), nullable=False),
    sa.Column('use_ssl', sa.Boolean(), nullable=False),
    sa.Column('use_tor', sa.Boolean(), nullable=False),
    sa.Column('tor_host', sa.String(length=64), nullable=False),
    sa.Column('tor_port', sa.Integer(), nullable=False),
    sa.Column('mempool_url', sa.String(length=255), nullable=False),
    sa.Column('price_source', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outbound_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(length=120), nullable=False),
    sa.Column('detail', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('price_usd', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('wtype', sa.String(length=20), nullable=False),
    sa.Column('xpub', sa.Text(), nullable=True),
    sa.Column('script_type', sa.String(length=20), nullable=False),
    sa.Column('gap_limit', sa.Integer(), nullable=False),
    sa.Column('onchain_mode', sa.String(length=20), nullable=False),
    sa.Column('address_type', sa.String(length=20), nullable=False),
    sa.Column('source_meta', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wallets_account_id'), ['account_id'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('amount_sats', sa.Integer(), nullable=False),
    sa.Column('fee_sats', sa.Integer(), nullable=False),
    sa.Column('price_usd', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('fiat_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('fiat_fee', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('fiat_source', sa.String(length=10), nullable=True),
    sa.Column('carried_basis_usd', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('carry_disabled', sa.Boolean(), nullable=False),
    sa.Column('transfer_reviewed', sa.Boolean(), nullable=False),
    sa.Column('txid', sa.String(length=80), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('counterparty', sa.String(length=120), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'source', 'external_id', name='uq_tx_account_source_external')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_wallet_id'), ['wallet_id'], unique=False)
        batch_op.create_index('ix_tx_account_ts', ['account_id', 'timestamp'], unique=False)
        batch_op.create_index('ix_tx_kind', ['kind'], unique=False)
        batch_op.create_index('ix_tx_txid', ['txid'], unique=False)

    op.create_table('utxos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('txid', sa.String(length=80), nullable=False),
    sa.Column('vout', sa.Integer(), nullable=False),
    sa.Column('value_sats', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=False),
    sa.Column('script_type', sa.String(length=24), nullable=False),
    sa.Column('chain', sa.Integer(), nullable=False),
    sa.Column('deriv_index', sa.Integer(), nullable=False),
    sa.Column('is_change', sa.Boolean(), nullable=False),
    sa.Column('label_kind', sa.String(length=40), nullable=False),
    sa.Column('created_height', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('spent_txid', sa.String(length=80), nullable=True),
    sa.Column('spent_height', sa.Integer(), nullable=True),
    sa.Column('spent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wallet_id', 'txid', 'vout', name='uq_utxo_wallet_outpoint')
    )
    with op.batch_alter_table('utxos', schema=None) as batch_op:
        batch_op.create_index('ix_utxo_account', ['account_id'], unique=False)
        batch_op.create_index('ix_utxo_spent_txid', ['spent_txid'], unique=False)
        batch_op.create_index(batch_op.f('ix_utxos_wallet_id'), ['wallet_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utxos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_utxos_wallet_id'))
        batch_op.drop_index('ix_utxo_spent_txid')
        batch_op.drop_index('ix_utxo_account')

    op.drop_table('utxos')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_tx_txid')
        batch_op.drop_index('ix_tx_kind')
        batch_op.drop_index('ix_tx_account_ts')
        batch_op.drop_index(batch_op.f('ix_transactions_wallet_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallets_account_id'))

    op.drop_table('wallets')
    op.drop_table('price_points')
    op.drop_table('outbound_log')
    op.drop_table('node_config')
    op.drop_table('llm_connections')
    op.drop_table('hourly_prices')
    op.drop_table('accounts')
    # ### end Alembic commands ###
